### ISSUE TITLE
GraphClient.explore() uses wrong path and method

### ISSUE THREAD

**Issue by oxymor0n** [elastic/elasticsearch-x-pack-py#1]
When I call `self.es_client.xpack.graph.explore('index_name', 'document_type', some_json_body)`, I get back the following error

    elasticsearch.exceptions.RequestError: TransportError(400, 'No handler found for uri [/index_name/document_type/_xpack/graph/_explore] and method [GET]')

See documentation at https://www.elastic.co/guide/en/x-pack/current/graph-api-explore.html#basic-search

**Comment by oxymor0n** [comment]
Further testing revealed that GET requests are fine (although POST requests are specified in the docs), but the path should be 

    /index_name/document_type/_xpack/_graph/_explore

instead of 

    /index_name/document_type/_xpack/graph/_explore

note the missing underscore in front of `graph`.

**Comment by honzakral** [comment]
The documentation (0) explicitly mention `_xpack/graph` with no underscore before `graph`. I haven't tested it myself yet, but either the docs is wrong or there is something else going on...

0 - https://www.elastic.co/guide/en/x-pack/current/graph-api-explore.html#basic-search

**Comment by oxymor0n** [comment]
Huh, that's interesting. I guess I've always skimmed through the docs 😅 Thanks for pointing that out.

Anyhow, if that's the case, then the docs is not consistent with the API, because the behavior I describe is real. Please see the attached screenshot, with the official Elasticsearch Docker running on the left, and the cURL commands on the right:

<img width="1440" alt="screen shot 2017-04-14 at 3 54 28 pm" src="https://cloud.githubusercontent.com/assets/2345378/25054403/f809b35c-212a-11e7-8ede-c27a6e93ffcf.png">

**Comment by honzakral** [comment]
Thank you, I have submitted a PR internally to fix the docs and will merge your PR shortly!

**Comment by honzakral** [comment]
Fixed via #2, thanks, @oxymor0n !
