### ISSUE TITLE
Unable to Access ML.py

### ISSUE THREAD

**Issue by rnama22** [elastic/elasticsearch-x-pack-py#3]
Hi,

I really appreciate the great effort. I would like to bring to your notice that I'm unable to access ml.py API through this package. When I downloaded the library using pip install, I wasn't able to find the ML associated files either. If that's not the case, Please let me know if I'm missing something. Thank you.

PS: I was able to access Monitoring, Info APIs

Rohith

**Comment by honzakral** [comment]
Hi, the `ml` package hasn't been uploaded onto pypi yet. I just uploaded it as `5.4.0` - https://pypi.python.org/pypi/elasticsearch-xpack/5.4.0
